checkId: 123

stages:
  - lint
  - build
  - test
  
tasks:
  BuildProject:
    stage: build
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: github.com/kubitre/for_diploma
    run:
      - go build -o main.bin main.go
    artefacts:
      - /main.bin

  LintProject:
    stage: lint
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: github.com/kubitre/for_diploma
    run: 
      - golangci-lint ../ > report.xml
    artefacts:
      - /report.xml
    services:
      - mongodb:latest:
        - name: mongoserv
        - ports: 12255:12255
      - rabbitmq:latest:
        - name: rabbit-dev
        - ports: 
          - 5672:5672
          - 15672:15672

  TestProject:
    stage: test
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: github.com/kubitre/for_diploma
    run:
      - go test ./...