taskID: 123

stages:
  - lint
  - build
  - test
  
jobs:
  BuildProject:
    stage: build
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: https://github.com/kubitre/for_diplom
    run:
      - go test ./...
    reports:
      allOutInfo: ^(?P<statusTest>FAIL|ok)\\s+(?P<Placement>[\\w_\\/]+)\\s+(?P<Time>[\\w.]+)$
      failedTest: "(?P<TEST>(--- FAIL: )(?P<TestName>[\\w]+)\\s+\\((?P<Time>[\\w.]+)\\))\n|(?P<Logs>\\s+(?P<fileName>[\\w_.]+):(?P<LineNumber>\\w+): (?P<LogText>.+)\n)"

  LintProject:
    stage: lint
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: https://github.com/kubitre/for_diplom
    run: 
      - golangci-lint ../ > report.xml
    artefacts:
      - /report.xml

  TestProject:
    stage: test
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: https://github.com/kubitre/for_diplom
    run:
      - go test ./...
