taskID: 123

stages:
  - lint
  - build
  - test
  
jobs:
  BuildProject:
    stage: build
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: https://github.com/kubitre/for_diplom
    run:
      - go build -o main.bin main.go
    artefacts:
      - /main.bin

  LintProject:
    stage: lint
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: https://github.com/kubitre/for_diplom
    run: 
      - golangci-lint ../ > report.xml
    artefacts:
      - /report.xml

  TestProject:
    stage: test
    image: [
      "FROM ubuntu:18.04 as env",
      "COPY dest1 /dest1",
      "RUN apt update && apt install --no-cache ffmpeg"
    ]
    repo: https://github.com/kubitre/for_diplom
    run:
      - go test ./...